README.md
idunn/blocks/wikipedia.py
idunn/utils/default_settings.yaml
idunn/utils/es_wrapper.py
tests/conftest.py
tests/docker-compose.yml
tests/fixtures/basket_ball.json
tests/fixtures/basket_ball_wiki_es.json
tests/test_api.py
tests/test_api_status.py
tests/test_full.py
tests/test_wiki_ES.py

Our intern elastic contains enough POI information to bypass the Wikipedia API.
If the request language belongs to the (comma separated string) list ES_WIKI_LANG, then we fetch this elastic, otherwise we request the Wikipedia API as we did before.

Bypass Wikipedia API

---

Pipfile
Pipfile.lock
idunn/blocks/opening_hour.py
idunn/blocks/services_and_information.py
idunn/utils/opening_hours_lib.py
tests/conftest.py
tests/test_accessibility.py
tests/test_api.py
tests/test_api_with_wiki.py
tests/test_full.py
tests/test_internet_access.py
tests/test_opening_hours.py
tests/test_wiki_ES.py

* Implement detailed "days" in "opening_hours"
* Work around multiple bugs in humanized_opening_hours (waiting for the next release that should solve these issues)
* Do not return "accessibility" block when all values are missing / unknown
* Improve "internet_access" block (using "internet_access" tag from osm)
* Use a session fixture in tests, to mock all external calls to wikipedia by default

Implement opening_hours "days", other blocks improvements

---

idunn/blocks/services_and_information.py
tests/fixtures/cinema_multiplexe.json
tests/fixtures/patisserie_peron.json
tests/test_accessibility.py
tests/test_api.py
tests/test_full.py
tests/test_wiki_ES.py

This PR adapts the accessibility block to the following specifications:
* if wheelchair and toilets:wheelchair are both undefined : no accessibility block
* if wheelchair and toilets:wheelchair are both defined with unknown values: no accessibility block
Simple tests (from the specifications) come along the changes.

tactile_paving removed

---

Pipfile
Pipfile.lock
idunn/blocks/wikipedia.py
idunn/utils/default_settings.yaml
tests/conftest.py
tests/docker-compose.yml
tests/test_rate_limiter.py

Because of standard API usage limitations, Idunn cannot make more than 200 requests per second to Wikipedia API.
This PR proposes a rate limiter upon a Redis service.
To activate the limiter you have to define the variable "WIKI_API_REDIS_URL".
If this variable is not set then Idunn doesn't limit its external requests number.

Wiki Rate Limiter

---

idunn/blocks/wikipedia.py
idunn/utils/default_settings.yaml
tests/conftest.py
tests/test_rate_limiter.py
tests/test_wiki_ES.py
tests/utils.py

When the Wiki ES service is down we want Idunn continue to deliver the correct information.
In this small patch we catch the 'connectionerror' to avoid the Idunn failure.
+ small test

Wiki ES timeout

---

idunn/blocks/opening_hour.py

The library ([tzwhere](https://pypi.org/project/tzwhere/)) that Idunn uses to associate a timezone to a POI location fails when the POI is close to an ocean (c.f. https://github.com/mattbornski/tzwhere/issues/8).
A small trick to avoid this problem is to force the timezone `forceTZ=True` which will return then the closest timezone.

forceTZ for costal points

---

idunn/blocks/wikipedia.py

Just add a catch to the most general redis exception raised by a lack of disk space.

Resilience to Redis fail

---

Dockerfile
Pipfile
Pipfile.lock
app.py
docker-compose.yml
gunicorn_logging.conf
idunn/utils/default_settings.yaml
idunn/utils/logging.py
idunn/utils/settings.py

The main thing is that we are now able to output json logs (for easier
ELK integration).
To enable it, the `IDUNN_LOG_JSON` must be set to 1.
`LOG_FORMAT` can be used to defined the logged fields / format
`LOG_LEVEL_BY_MODULE` can be set to define the log level for each module
Gunicorn now also output its log as json (and this is not configurable,
it's set in the Dockerfile)
should close #21

Add more logging facility for idunn

---

docker-compose.yml
prometheus/graphana_dashboards.json
prometheus/graphana_dashboards_provisioner.yaml
prometheus/graphana_datasource.yaml
prometheus/prometheus-compose.yml
prometheus/prometheus.yml
prometheus/readme.md

Add a dev prometheus/grafana setup to see the metrics
These are dev prometheus setup to see Idunn's metric.
This is absolutely not to be used in production!
To test it, you need to run the idunn's docker-compose with the additional prometheus compose. 
In the main idunn's directory:
`docker-compose -f docker-compose.yml -f prometheus/prometheus-compose.yml up --build`
Then you can query idunn on `localhost:5000` and access graphana on `http://localhost:3000/d/idunn_1/idunn-dashboard`.
(graphana's accesses are user: `admin`, password: `admin`).
If you change the dashboard, don't forget to export to json  and change the file `graphana_dashboards.json`.
NOTE: the dashboard is not complete, lots of metrics will need to be added after #30 
the dashboard look like this:

Grafana dashboard for prometheus metrics

---

idunn/blocks/wikipedia.py

RedisError was catch in the rate limiter and in the init_cache() but not in the cache.
This PR just proposes to catch it also in the cache in order to prevent any Redis interruption.

Catch Redis interruption

---

idunn/api/status.py
tests/test_api_status.py

add a `ready` field  in `/status` to have an easy readyness probe

add a ready status

---

Pipfile.lock
idunn/blocks/wikipedia.py
idunn/utils/redis.py
tests/conftest.py
tests/test_api_circuit_breaker.py
tests/test_cache.py
tests/test_rate_limiter.py
tests/test_wiki_ES.py

* Cache will not try to resolve wikipedia content if redis is not reachable
* Define `get_redis_pool` function in utils, to refactor Redis initialization
* Rate-limiter and cache connections are set to `DISABLED_STATE` (more explicit and less confusing than `False`) when these features are not enabled in settings

Do not fetch wiki content if cache is not reachable

---

Pipfile
Pipfile.lock
README.md
idunn/api/places.py
idunn/api/places_list.py
idunn/api/utils.py
idunn/places/pj_poi.py
idunn/utils/categories.yml
idunn/utils/geometry.py
tests/test_categories.py
tests/test_pj_poi.py
tests/test_places.py
tests/utils.py

* `list` verbosity does not contain "information" block (including wikipedia info) contrary to `long`, and is used by default on GET /places?bbox=...
* `source` parameter can be used by the client to force the source selection. Eg: `?source=osm`

Implement source param and a new verbosity when fetching multiple places

---

idunn/blocks/opening_hour.py
idunn/places/pj_poi.py
idunn/utils/default_settings.yaml
tests/test_pj_poi.py

* solar hours should be computed only when necessary (unfortunately hoh always initializes SolarHours if `location` is set)
* shorter version of raw opening hours in `PjPOI`

Optimize opening hours parsing

---

app.py
idunn/blocks/opening_hour.py
idunn/places/pj_poi.py
idunn/utils/logging.py
tests/test_opening_hours.py

* Fix memory leak in event_hooks
* Catch parser error (`LarkError`) that are sometimes not caught by hoh library
* Parse variants of "24/7" opening hours correctly
* Add request URL to "unhandled error" object

Fix memory leak and improvements about error handling

---

app.py
idunn/api/closest.py
idunn/api/places.py
idunn/api/urls.py
idunn/utils/app.py
idunn/utils/prometheus.py
tests/test_api.py
tests/test_closest.py

* Validate float values, and accept negative values using werkzeug syntax https://werkzeug.palletsprojects.com/en/0.15.x/routing/#werkzeug.routing.FloatConverter
* Work around bug in apistar that may cause the injector cache to be polluted with incomplete dependency resolution. Fixed using a custom `IdunnApp` class.

Validate URLs with float, fix bug in apistar injector

---

idunn/utils/settings.py

Overriding a setting value with `true` string in environment variable was broken because of two consecutive `if`.

Fix boolean setting value set by environment

---

idunn/directions/models.py
tests/fixtures/directions/combigo_directions_publictransport.json

All fields in `TransportInfo` are now optional to handle "num" in "walk" steps.

combigo: Fix transport info in walk steps

---

idunn/places/base.py
tests/fixtures/street_birnenweg.json
tests/test_closest.py
tests/test_places.py

Use street name and label in `address` object as fallback.  
This is especially useful for `latlon` places where the API may return both an address or a street, depending on what is found on reverse search.
NB: For clarity, a street name is renamed in fixtures files. "9a Birnenweg" looks too much like an address.

places: Fallback to street name and label when address is not defined

---

idunn/blocks/wikipedia.py
idunn/utils/circuit_breaker.py
idunn/utils/default_settings.yaml
tests/test_api_circuit_breaker.py
tests/test_wiki_size_limit.py

The existing circuit breaker was implemented specifically for Wikipedia APIs. 
This PR defines a new `IdunnCircuitBreaker` that will be reused for all external APIs (weather, etc.)

Define reusable circuit breaker

---

docker-compose.yml
idunn/api/directions.py
idunn/blocks/wikipedia.py
idunn/utils/default_settings.yaml
idunn/utils/rate_limiter.py
idunn/utils/redis.py
tests/test_cache.py
tests/test_rate_limiter.py

* Define a new class `IdunnRateLimiter` using the existing mechanism (based on redis_rate_limit).
* Implement a limit per client, based on request headers
* Add an option to ignore Redis errors (not ideal, that will do for now, in order to reuse existing idunn-redis service)

Refactor rate limiter and define limits on directions endpoint

---

idunn/utils/rate_limiter.py
tests/test_directions.py

The HTTP response with status 429 was not tested.  
This will be make the migration of this behavior easier in #100

Add a test case about rate limited response

---

app.py
idunn/api/places_list.py
idunn/utils/encoders.py
tests/test_kuzzle.py

Besides tweaking the parameters validation, it is also necessary to define a custom formatter for datetimes, in order to preserve the same format.

Fix kuzzle tests with FastAPI

---

idunn/api/directions.py
idunn/directions/client.py
tests/test_directions.py

Allow extra params in directions requests with mode `driving`, `cycling`, `walking`, that are currently hardcoded in external API calls.
This fixes requests with `?exclude=ferry`, where this parameter was ignored.

directions: Forward mapbox specific params in API call

---

app.py
idunn/directions/client.py
idunn/utils/logging.py
idunn/utils/prometheus.py
idunn/utils/settings.py

* Call `init_logging` on first `settings` import  
If `init_logging` is called after other imports (which initialize their own `logger`) the logging configuration would be ignored.
* Add log message about directions calls (was removed in #101)

Fix logging initialization

---

idunn/api/directions.py
idunn/api/pages_jaunes.py
idunn/api/places.py
idunn/api/pois.py
idunn/api/urls.py
idunn/api/utils.py
idunn/directions/client.py
idunn/places/__init__.py
idunn/places/exceptions.py
idunn/places/latlon.py
idunn/places/place.py
idunn/places/utils.py
idunn/utils/default_settings.yaml
tests/fixtures/street_birnenweg.json
tests/test_cache.py
tests/test_directions.py
tests/test_opening_hours.py
tests/test_pj_poi.py
tests/test_places.py
tests/utils.py

**GET**  `/v1/directions?origin=osm:node:4242&destination=latlon:2.9:12.3&type=publictransport`
where `origin` and `destination` are place ids.
It is now possible for the server to fetch details about the places used as origin and destination, and implement specific behavior for public transports stops.
This comes in addition to the existing route
**GET** `/v1/directions/{f_lon},{f_lat};{t_lon},{t_lat}`  
(with explicit latitudes and longitudes in the URL path)
Except the new `origin` and `destination`, the new route accepts the same query parameters (`type`, `language`, etc.)
----
By default, Idunn will now fetch POIs from both `munin` index (shared with the geocoder) and `munin_poi_nosearch` (introduced by https://github.com/QwantResearch/fafnir/pull/40) containing extra POIs that are …

New directions endpoint with place id parameters

---

idunn/api/pages_jaunes.py
idunn/api/utils.py
tests/test_api.py

`filter` queries are executed as post filters by Elasticsearch (and are actually renamed to `post_filter` in recent versions). 
They are significantly slower than bool query (with "filter" nested in a `query` object).
The ES query duration drops from ~50ms to ~1 or 2ms !
See https://stackoverflow.com/a/29131858/5634396 for more details

Optimize queries to fetch by id in Elasticsearch

---

.travis.yml
Dockerfile
Pipfile
Pipfile.lock
README.md

The main motivation for this change is to limit the number of threads used by FastAPI.
FastAPI + Starlette use the [`ThreadPoolExecutor`](https://docs.python.org/fr/3.8/library/concurrent.futures.html?highlight=concurrent#concurrent.futures.ThreadPoolExecutor) internally to handle non-async routes.
In Python <3.8, the maximum number of workers used by this executor is `os.cpu_count() * 5`.
That is unnecessary high on machines with >=32 cpus, where multiple instances of Idunn may be launched.
See https://github.com/tiangolo/fastapi/issues/603 for more details.
In Python 3.8, the number of workers is bounded to 32, which is more reasonable.
We could workaround this default value differently, but Python 3.6 also lacks some features that could be handy in the future, such as [Postponed …

Upgrade from Python 3.6 to Python 3.8

---

app.py
idunn/api/urls.py
idunn/utils/default_settings.yaml
pyproject.toml

Define 2 new settings values:
* `DOCS_ENABLED`: to enable `/docs` endpoint provided by FastAPI (disabled by default)
* `DOCS_URL_PREFIX`: the base path used to access the OpenAPI schema 
(required when Idunn is deployed behind a reversed proxy with a path different from `/`)

Define settings to enable /docs endpoint with custom path prefix

---

idunn/directions/models.py

Defines a validator for `lineColor` to always return a valid hexadecimal color code.  
This change is a workaround for cases when leading zeros are missing in the response from the external API.

directions: Define validator for "lineColor"

---

idunn/geocoder/nlu_client.py
idunn/utils/default_settings.yaml
tests/test_autocomplete.py

It appears that "tagger" is a more appropriate name to describe the nature of this endpoint.

nlu_client: rename tokenizer -> tagger

---

Pipfile
Pipfile.lock

* httpx 0.12 adds support for `no_proxy` environment variable, used by our instances of Idunn to connect to internal APIs
https://github.com/encode/httpx/blob/master/CHANGELOG.md#0120-march-9th-2020

Upgrade dependencies, including httpx 0.12.0

---

idunn/blocks/covid19.py
idunn/places/base.py
idunn/places/event.py
idunn/places/pj_poi.py
idunn/places/place.py
tests/fixtures/address_du_moulin.json
tests/fixtures/admin_goujounac.json
tests/fixtures/blancs_manteaux.json
tests/fixtures/cinema_multiplexe.json
tests/fixtures/louvre_museum.json
tests/fixtures/orsay_museum.json
tests/fixtures/patisserie_peron.json
tests/fixtures/street_birnenweg.json
tests/test_categories.py
tests/test_full.py
tests/test_kuzzle.py
tests/test_places.py

* Define `Address` model, used in existing `Place` response model
* Implement `.get_country_code()` for all places  
This method returns the least specific country code among all codes defined in administrative regions.
* Add `country_code` field in address objects

Place model: add 'country_code' in address object

---

idunn/blocks/images.py
tests/test_wiki_images.py

The `alt: str` property for images is derived from the poi name.
But the case when no name is available was not handled.

Fix: images block fails when POI has no name

---

idunn/blocks/covid19.py
idunn/places/base.py
idunn/utils/covid19_dataset.py
idunn/utils/default_settings.yaml
idunn/utils/redis.py
tests/docker-compose.yml

_These 3 commits may be reviewed separately_
* More explicit messages about Redis errors 
* Clean opening status logic in covid19 block
* use Redis data in priority (maintained by CaResteOuvert, and refreshed more regularly)
* handle "open" and "restricted" values for `opening_hours:covid19`
* Define a list of country codes in settings where covid19 block should be enabled

Consolidate POI status related to covid-19, improve error handling

---

idunn/blocks/covid19.py
tests/test_covid19.py

A little oversight that was merged with #131

covid19: Fix opening_hours:covid19 parsing

---

idunn/geocoder/nlu_client.py

This should help to reduce the noise caused by irrelevant `intentions` about raw queries that are tagged incorrectly as potential categories.

NLU intentions: ignore isolated query about non-classified category

---

idunn/api/places_list.py
idunn/geocoder/bragi_client.py
idunn/places/__init__.py
idunn/places/base.py
idunn/places/poi.py
pyproject.toml
tests/conftest.py
tests/fixtures/autocomplete/carrefour_in_bbox.json
tests/test_autocomplete.py
tests/test_places_by_query.py
tests/utils.py

Search for places with `bbox` and full-text query `q` is now possible among OSM data !
A few notes:
* this PR defines `pois_query_in_bbox` to use Bragi's `POST /autocomplete` with a geojson shape in body to filter search results contained in bbox.
* `get_places_bbox` endpoint is now async to call the `BragiClient`. FastAPI's `run_in_threadpool` is used to call pre-existing I/O-blocking functions in separate threads.
* a new `BragiPOI` adapter is required, as the POI format returned by Bragi is slightly different than raw data stored in Elasticsearch. This part is quite ugly.  
In the longer term, we could consider implementing all bbox searches with Bragi.
But this would require some delicate changes about how class/subclass filters are implemented.

Implement POIs search by bbox and query via Bragi

---

idunn/geocoder/nlu_client.py
tests/test_autocomplete.py

In the first implementation, an `Intention` with full-text query was returned only when `pj_source` was available for the current focus point (i.e in France).
Now that #134 introduces full-text queries for all data sources, this condition can be removed. 
As a consequence, a query with a brand name may also be returned if no focus is set. We need to check if this behavior is expected and that the front-end application will behave correctly in this case.

NLU: allow full-text query outside France and without focus

---

idunn/api/places.py
idunn/api/utils.py
idunn/places/exceptions.py
idunn/places/utils.py
tests/test_places.py

Ids for addresses currently use this pattern: `addr:<lon>;<lat>:<house_number>`.  
They may not be stable in the long term, especially if multiple data sources are used to import addresses, or because of rounding discrepancies. 
This PR suggests to redirect requests about unknown `addr:` objects to equivalent `latlon:` objects (where reverse geocoding may be used) when `lat` and `lon` values can be extracted from their id.  
In this case a HTTP 303 ("See other") response is returned.

Redirect unknown address id to equivalent latlon

---

idunn/api/places.py
tests/test_places.py

A small oversight to fix, following #137 
Trailing slashes are actually not a problem in this case, but it would be cleaner to avoid successive `//` in the redirected URL.

Ignore trailing slash in url prefix used for redirected location

---

idunn/blocks/wikipedia.py
idunn/geocoder/nlu_client.py
idunn/utils/circuit_breaker.py
idunn/utils/default_settings.yaml

Implement a circuit breaker for NLU endpoints.
This shares the same behavior as Wikipedia's circuit breaker which means:
- ~~it shares the same settings for timeout (defaults to 120s) and max fails (defaults to 20), it would need more changes to be able to customize this (but I don't think we actually care?)~~
- when the max tries are reached without success, the API calls will be skipped until the timeout is elapsed, then the next call will trigger the timer again if it fails again
I did override the `call_async` method from pybreaker, which should not be helpful in Idunn since it appears it is only [compatible with the asyncs from Tornado framework](https://pypi.org/project/pybreaker/#optional-tornado-support).

add a circuit breaker for NLU API's

---

idunn/blocks/covid19.py
idunn/utils/default_settings.yaml
tests/test_covid19.py

This PR implements a new flag `COVID19_BLOCK_KEEP_STATUS_UNKNOWN`, False by default.
As a consequence, the block `covid19` will no longer be returned about POIs for which no specific data is available (i.e. when the `status` in this block is `unknown`).

Covid-19: exclude block from response if opening status is 'unknown'

---

idunn/blocks/recycling.py
idunn/datasources/recycling.py
idunn/utils/default_settings.yaml

Implement `RECYCLING_MEASURES_MAX_AGE_IN_HOURS` in settings.  
Measures older than this threshold will be filtered out by the query to the data source.

Recycling: Configure measures max age

---

idunn/api/constants.py
idunn/api/places_list.py
idunn/api/urls.py
idunn/api/utils.py
idunn/places/pj_poi.py
tests/test_categories.py
tests/test_places_by_query.py

* `/v1/places` endpoint accepts a new boolean parameter: `extend_bbox` (false by default). If this parameter is set to true and no results are found in the original `bbox`, a second query will be executed on an extended bbox and its results will be returned instead.
* In addition to the `places` list and `source`, 2 new fields are present in the response:
* `bbox`: The minimal bbox containing all results. `null` if no place is found.  
It may be **larger** than or **outside** of the original bbox passed in the query if `extend_bbox=true` was set.
* `bbox_extended` (bool): true if `extend_bbox=true` was set and a second search has been executed, after no results were found in the original bbox included in the URL.
This new option should enable the front-end application to adapt the view to …

Implement "extend_bbox" parameter on /places endpoint

---

idunn/geocoder/nlu_client.py

Add one line of logs each time intention is checked, which should be convenient to build metrics about it usage.
I integrated as much details as possible about results of external calls in case we want to performed more refined analysis. I don't think I am missing any exciting data to add?

add more logs for intention results

---

idunn/geocoder/nlu_client.py
idunn/utils/default_settings.yaml

`poi` is the default value for `domain`, but other instances may expose other model names.

nlu: Make tagger and classifier 'domain' configurable

---

idunn/api/places_list.py
idunn/utils/default_settings.yaml

The extent of the extended bbox was hardcoded, and may be too large for queries located in dense areas.
This PR makes this value configurable, and updates the default value from 0.8 to 0.4°.
cc @bbecquet @G-Ray

Places list: make extended bbox size configurable, and reduce default value

---

idunn/utils/logging.py

Because of some obscure interaction with gunicorn and the `UvicornWorker` we are using in the Docker image, the unhandled exceptions were not logged with the expected json formatter.
This is also due to how the `--preload` option is used with gunicorn, to load the app before all workers are initialized (and might define their own logger configuration).

Fix unhandled exception logger format when app is preloaded by gunicorn

---

idunn/places/pj_poi.py
tests/test_pj_poi.py

Fill `admins` field with city information for POI addresses from PJ.
From `<IDUNN>/v1/places?bbox=2.327,48.852,2.347,48.857&category=pharmacy` (removing most fields other than `address`):
```json
"places": [{
"type": "poi",
"id": "pj:01546115",
"name": "Citypharma",
"address": {
"id": null,
"name": "26 rue du Four",
"label": "26 rue du Four, 75006 Paris",
"housenumber": "26",
"street": {  },
"postcode": "75006",
"admins": [
{
"id": null,
"name": "Paris",
"label": "Paris (75006)",
"class_name": "city",
"postcodes": [
"75006"
]
}
],
"admin": null,
"country_code": "FR"
}
}]
```
The only field from [`AdministrativeRegion`](https://github.com/QwantResearch/idunn/blob/master/idunn/places/place.py#L18-L23) left empty is the `id`.

add city informations in admins for PJ POIs

---

idunn/geocoder/bragi_client.py

`ConnectTimeout` errors have been noticed in some cases in our deployed environments.
These errors caused unhandled exceptions.
This PR defines an explicit error message in this case, to make the investigation easier.

Add explicit error message on connect timeout to Bragi

---

idunn/api/geocoder.py
idunn/utils/default_settings.yaml

When `AUTOCOMPLETE_NLU_SHADOW_ENABLED` is true, intentions are always retrieved for each /autocomplete call, independently of whether `?nlu` is set or not.
This is useful to measure the impact of these calls, before the feature is effectively used by the application.

Define setting to call NLU APIs as dry run

---

idunn/api/utils.py
idunn/blocks/services_and_information.py
tests/test_accessibility.py
tests/test_api.py
tests/test_api_circuit_breaker.py
tests/test_api_with_wiki.py
tests/test_cache.py
tests/test_covid19.py
tests/test_full.py
tests/test_places.py
tests/test_rate_limiter.py
tests/test_recycling.py
tests/test_wiki_ES.py
tests/test_wiki_images.py
tests/test_wiki_size_limit.py

A lot of trailing commas where kept by black when it merged multi-line calls into a single line. I suppose we can remove them once and for all as it's quite ugly.

remove unnecessary trailing commas

---

idunn/utils/opening_hours.py

Initializing the js context with the app caused timeout, because v8 does not seem to support to be forked. 
The Idunn process is forked when it's run with the gunicorn `--preload` option.

opening_hours: MiniRacer ctx should not be forked on app initialization

---

idunn/places/base.py
tests/test_categories.py
tests/test_full.py

This is mainly relevant for streets, that may be cover multiple postcodes.  
And the current format that joins the values with `;` is not useful for the applications.

places: Set postcode to null in 'address' when data contains multiple postcodes

---

idunn/geocoder/nlu_client.py
tests/fixtures/autocomplete/nlu/with_poi.json
tests/test_autocomplete.py

This PR fixes a little oversight in how tokens returned by the NLU tagger are filtered.

nlu: tokens tagged as "POI" were not correctly ignored

---

idunn/geocoder/models/params.py
idunn/utils/default_settings.yaml

Take benefits of https://github.com/CanalTP/mimirsbrunn/pull/417 to allow a larger focus mode with larger zoom levels.
The endpoint `autocomplete` takes a new optional parameter `zoom` to pass the current zoom level of the front-end, which is used to decide the typical expected distance of results. I am using [this branch](https://github.com/QwantResearch/erdapfel/pull/743) of erdapfel to test this change:
| Z = 3 | Z = 5 | Z = 7 | Z = 9 | Z = 11 |
|:----------------:|:-----:|-------|-------|-------------------------------|
| ![Screenshot_2020-08-19_15-49-50](https://user-images.githubusercontent.com/1173464/90643685-21b66600-e234-11ea-8bc8-8cceae6c2d06.png) | ![Screenshot_2020-08-19_15-50-11](https://user-images.githubusercontent.com/1173464/90643722-2aa73780-e234-11ea-9215-5d775af7ba05.p …

add radius parameter for the geocoder

---

idunn/geocoder/models/params.py
idunn/utils/default_settings.yaml
idunn/utils/math.py

This follows https://github.com/QwantResearch/idunn/pull/162, adding a behavior to round even more coordinates provided by erdapfel before sending them to the back-end. The benefits of this would be to optimize the utilization of the cache we have on top of the geocoder.

focus: stronger rounding of coordinates for larger zoom level

---

idunn/places/base.py
idunn/places/event.py
idunn/places/pj_poi.py
tests/test_full.py

This is a minor improvement to make the address/context formatting more user-friendly in the application.

places: Use user language for 'admins' names and labels

---

idunn/geocoder/nlu_client.py
idunn/utils/categories.yml
tests/test_autocomplete.py
tests/test_categories.py

* The NLU client skips the call to the classifier for "brand" queries. However we noticed the tagger may not make the distinction between "category" and "brand" reliably.  
As a workaround, this PR suggests to remove the `skip_classifier` mechanism, and to always call the "regex" classifier, and try to classify the brand query with a subset of the list of categories. These categories are tagged with `match_brand: True` in "categories.yml".
* `recycling` is currently the only category with `match_brand: True`
* Add 3 new categories: `station`, `parking`, and `place_of_worship`.

nlu: Add new categories, and allow some categories to be classified from 'brand' queries

---

idunn/geocoder/nlu_client.py

Return an explicit category name provided by the classifier only if it belongs to the set of expected categories for Idunn.
With current behavior, if the classifier returns a category not referenced in Idunn, it will be likely to be ignored by Erdapfel and would result in a invalid call to `api/places` otherwise.

nlu_client: make sure returned category is valid

---

idunn/blocks/opening_hour.py
idunn/utils/data/opening_hours_wrapper.js
idunn/utils/opening_hours.py
tests/test_opening_hours.py

"opening_hours.js" support public holidays in a certain list of countries: https://github.com/opening-hours/opening_hours.js#holidays
Opening hours evaluation should ignore PH clauses in the other countries, to return opening hours for a typical week.

opening hours: Ignore public holidays in countries where opening_hours.js does not support them

---

idunn/api/geocoder.py

In #172, geocoded features were used to exclude irrelevant intentions where the query does not match enough results.  
As this behavior is specifically designed to match brand names or shop categories, features that are not POIs should not be counted.

autocomplete: Count POIs only when controlling intention with query

---

idunn/api/geocoder.py
idunn/geocoder/nlu_client.py

Add some detail on the reason why a request to the nlu client is aborted. 
This is a simple implementation that will just raise an exception holding a human-readable explanation.

nlu_client: log decisions to skip NLU

---

idunn/api/directions.py
idunn/api/instant_answer.py
idunn/api/places.py
idunn/api/utils.py
idunn/datasources/pages_jaunes.py
idunn/places/__init__.py
idunn/places/exceptions.py
idunn/places/utils.py

Several different exceptions have been defined to handle these errors, but they were difficult to catch properly.
This PR suggests to derive all these errors from a new `IdunnPlaceError`, and fixes some oversights:
* Unknown id for `ApiPjSource` will now raise `PlaceNotFound`. 
As a consequence `/v1/places/<id>` will return a status 404 instead of 500 in this case.
* `/v1/directions` will accept redirected place ids as `origin` or `destination`
(e.g. unknown `addr:` are redirected to their equivalent `latlon:`)

Clean up error handling on /places/<id> and place_from_id

---

idunn/api/instant_answer.py
tests/fixtures/autocomplete/__init__.py
tests/test_instant_answer.py

Fixes an oversight in #180  
Places returned by `get_places_bbox` are instances of `Place` model , and its properties should be accessed via attritbutes.

instant_answer: Fix place id getter on single result from an intention

---

idunn/api/instant_answer.py
tests/test_instant_answer.py

Small adaptation of `InstantAnswerResponse`: the previous object is wrapped into `data.result`.

Adapt /v1/instant_answer response format to other IAs

---

Pipfile
Pipfile.lock
app.py
idunn/utils/default_settings.yaml
tests/fixtures/autocomplete/__init__.py
tests/test_api_status.py
tests/test_autocomplete.py

* `FastAPI` 0.55 :arrow_right: 0.63
* `httpx` 0.13 :arrow_right: 0.16
Other changes are mostly related to respx : https://lundberg.github.io/respx/upgrade/

Upgrade FastAPI and related dependencies

---

app.py
idunn/api/places.py
idunn/api/urls.py
idunn/utils/default_settings.yaml
tests/test_accessibility.py
tests/test_api.py
tests/test_places.py
tests/test_wiki_images.py

[`CORSMiddleware`](https://fastapi.tiangolo.com/tutorial/cors/#cors-cross-origin-resource-sharing) is provided by FastAPI (actually reexported from Starlette).
Its behavior complies better with the standard. Especially, `Access-Control-Allow-Origin` header will be returned only when `Origin` is defined in the request.

Use standard CORSMiddleware instead of custom implementation

---

Pipfile
Pipfile.lock
idunn/api/instant_answer.py

See https://fastapi.tiangolo.com/advanced/custom-response/?h=orjson#use-orjsonresponse   
and https://fastapi.tiangolo.com/advanced/response-directly/ 
for more details about this change.
This also prevents a double validation after `InstantAnswerResponse` has been created in `build_response`. By default, FastAPI would re-validate the response model when creating the JSON response.

optim: Return ORJSONResponse directly for instant_answer

---

idunn/datasources/pages_jaunes.py
tests/test_categories.py
tests/test_pj_poi.py

An oversight in #174 that could not be noticed in environment where the legacy source is no longer used.

Fix LegacyPjSource to use CategoryEnum methods

---

.pylintrc
idunn/api/instant_answer.py
idunn/instant_answer/__init__.py
idunn/instant_answer/normalization.py
idunn/instant_answer/patterns_to_ignore.txt
idunn/utils/default_settings.yaml
idunn/utils/maps_urls.py
tests/test_instant_answer/test_ia_api.py
tests/test_instant_answer/test_ia_normalization.py

This PR introduces
* a "patterns_to_ignore.txt " file, with regex to remove at the start and end of queries for instant answers
* a new flag `IA_SUCCESS_ON_GENERIC_QUERIES`, to return a successful response with empty results on queries with no substantial input. This is useful when the client would like to handle that case specifically, with a generic map for example.

Instant answer: normalization by removing common patterns in queries

---

idunn/blocks/website.py
idunn/places/pj_poi.py
tests/test_categories.py
tests/test_full.py
tests/test_places.py
tests/test_website.py

To simplify client-side implementations, the `website` block will always contain a non-empty `label`.

Website block: always return a 'label', use domain name by default

---

idunn/places/base.py
idunn/places/models/pj_find.py
idunn/places/models/pj_info.py
idunn/places/pj_poi.py
idunn/places/place.py
idunn/places/poi.py
idunn/utils/default_settings.yaml
tests/test_categories.py
tests/test_full.py
tests/test_places.py

In the `meta` object:
* `source_url` is a direct URL to the place details
* `contribute_url` is defined for OSM POIs only

Define source_url and contribute_url in place meta

---

idunn/blocks/contact.py
tests/test_contact.py
tests/test_full.py

Exposes the raw email address, in addition to the "mailto:" URL.

Add 'email' field in contact block

---

idunn/utils/categories.yml
tests/test_categories.py

Simplify categories that require a non-trivial request to the source.
There is some arbitrary stuff going on, but it should be simpler to discuss it now that there is a base suggestion.

simplify complex categories

---

idunn/datasources/pages_jaunes.py

It has been noticed that different result pages from the API may contain duplicated POIs.
This PR suggests to remove these duplicated items. As a result, the number of places in the response, may be strictly less than the requested "size", even if more places would have been available in following pages.

PJ API: Remove places with duplicated merchant_id from results

---

idunn/utils/result_filter.py
tests/fixtures/autocomplete/__init__.py
tests/fixtures/autocomplete/paris.json
tests/test_instant_answer/test_ia_api.py
tests/test_result_filter.py

Read from translation fields while filtering instant answer's output. This should mainly help when the content of the query is not consistent with parameter `lang`.

result_filter: check translated names

---

idunn/instant_answer/patterns_to_ignore.txt
idunn/utils/categories.yml
tests/test_instant_answer/test_ia_normalization.py

After internal feedbacks and observations of my own.

Minor adjustments on instant answers triggers and normalization

---

idunn/api/instant_answer.py
idunn/api/places_list.py
idunn/places/base.py

This change is meaningful for intentions where the related `place` is a POI (without bbox).
In this case, the search bbox is defined arbitrary around this point. This did not guarantee that the nearest results would appear at the top of the list.
In this specific case, this PR suggests to sort results by distance from the reference point, for relevance purposes.

Instant answers: sort places by distance from intention POI point

---

idunn/api/instant_answer.py
idunn/api/urls.py
idunn/utils/ban_check.py
idunn/utils/default_settings.yaml
tests/test_instant_answer/test_ia_api.py

For instant answers only at this point:
* Integrate "ban redis" mechanism: return 429 status code for clients found in redis
* Limit query length (to 100 chars by default)

Anti scraping integration

---

idunn/api/instant_answer.py
idunn/utils/prometheus.py
idunn/utils/result_filter.py

Each commit can be reviewed independently
- count and time all requests in Prometheus metrics, including `HTTPException` with error status codes, and other exceptions
- update "result_filter" log level
- add log messages about  instant answer responses, to be able to analyze the proportion of valid responses based on these logs

Monitoring and logging adjustments for instant answers

---

idunn/places/pj_poi.py
tests/fixtures/pj/musee_picasso.json
tests/test_pj_poi.py

Build affiliation links instead of using links provided by the API to avoid slight privacy concerns.
The most naive approach would be to provide `https://www.pagesjaunes.fr/pros/{merchant_id}#blocAvis` ~~but we still want to allow some metrics so I kept `https://www.pagesjaunes.fr/partenaire?id={merchant_id}&component=review&action=view&xtor=AD-350-[QWANT]-[CONTRIBUTIF]-[VOIR_TOUS_AVIS]` from production.~~

pagesjaunes: build affiliation links

---

idunn/utils/ban_check.py
tests/test_instant_answer/test_ia_bancheck.py

Fixes an oversight in #209 where an `HTTPException` was re-caught immediately with another status code :facepalm:

Bancheck: fix status code for banned client

---

idunn/geocoder/nlu_client.py
idunn/utils/default_settings.yaml
tests/fixtures/autocomplete/classif_pharmacy.json
tests/test_nlu_client.py

Make use of the provided weights from the classifier:
- check that the special category `unk` (understand "unclassified") is missing or negligible
- check that the result has a big weight
- check that there is not several categories with a big weight
This is based on [this function](https://git.qwant.ninja/r.dupre/scripts/-/blob/master/util/nlu.py#L55-87) that I had tested [here](https://git.qwant.ninja/r.dupre/scripts/-/blob/master/check_ia_classification.py). The default settings were chosen by testing many combinations through [this script](https://git.qwant.ninja/r.dupre/scripts/-/blob/master/classif-params/src/main.rs) (which actually seems overkill, arbitrary values would have probably worked fine).

nlu_client: use classifier weights to ignore ambiguous results

---

idunn/datasources/pages_jaunes.py

A list item with `"id": null` would break the client application as no valid URL can be used to fetch the place detais.

PJ: Ignore places without merchant_id in response list

---

idunn/utils/result_filter.py

For example, the query word "la" will no longer match the label word "da".

ia: Strict match for label words with less than 2 characters

---

idunn/api/instant_answer.py
idunn/api/urls.py
tests/test_instant_answer/test_ia_api.py

To disambiguate between absence of results and actual errors.

ia: Return status 204 instead of 404 when no instant answer to display

---

idunn/utils/result_filter.py
tests/conftest.py
tests/fixtures/address_43_rue_de_paris.json
tests/fixtures/autocomplete/43_rue_de_paris_rennes.json
tests/fixtures/autocomplete/__init__.py
tests/test_instant_answer/test_ia_api.py
tests/test_result_filter.py

Bragi uses "house" as the "type" for addresses items, both in query parameters and responses.  
As described in: https://github.com/Qwant/idunn/blob/b4f65bd9bd7be04c87fb6e11ee7448f9c73dcc6f/idunn/api/utils.py#L37-L43
It is a source of confusion as `address` is used in Idunn responses.  
A test case has been added to reproduce the issue. There are a lot of moving pieces in this mechanism, so 2 fixtures files are required (autocomplete response + raw ES document).

ia: Fix address ranking. Bragi returns type `house` and not `address`

---

idunn/utils/categories.yml
idunn/utils/result_filter.py
tests/test_categories.py

Extend the list of categories to match what the classifier can identify.
Some updates to karthoterian_docker (WIP) are required to cover all the POIs and categories, especially:
- restaurant types, I think we can match on the `cuisine` tag prior to `leisure` in order to set `class,subclass` = `restaurant,cuisine_type`.
- I removed diet-related categories since it would be quite annoying to add this information right now (I have a few ideas but they are all quite hacky)
- we could match more subkeys for some tags : tourism, historic

extend the list of categories

---

idunn/datasources/pages_jaunes.py

Use fixed number of decimals in bbox format used in PJ API.  
For some small float values the default string format uses a scientific notation that is not supported by the API.  
Also the order of the parameters is updated to stick to the documentation, even if it does not seem to have any impact.

pj: Fix bbox format in some rare cases

---

idunn/api/directions.py

This call to `rate_limiter.check_limit_per_client` is redundant with the `directions_request` dependency shared by "get_directions" and "get_directions_with_coordinates" routes.
This has no impact, as this route "get_directions" (used by place ids as parameters) is not currently used by the application.

Remove redundant rate limit check on directions by ids route

---

idunn/api/geocoder.py
idunn/api/instant_answer.py
idunn/api/search.py
idunn/api/urls.py
idunn/geocoder/models/geocodejson.py
tests/test_search.py

This mostly reuses code from `instant_answer` but I tried to change the API a bit to be more consistent with what we usually use internally between erdapfel and Idunn:
- the answer format is simpler, either consisting of the same format as `get_place` (through key `place`) or the format of `get_bbox_places` (through key `bbox_places`)
- we don't usually raise error codes 404 when we have an empty geocoder result, I tried to stick with this by returning an empty result
The only slight behavior change is that there is no truncating of the input query, maybe we should add a global parameter for this? I've also thought about skipping normalization since it would seem weird to "ignore or change part of what is in the search bar" but this seems like a free potential improvement of results?
Part …

add endpoint `search`

---

idunn/api/geocoder.py
idunn/api/instant_answer.py
idunn/api/search.py
idunn/geocoder/nlu_client.py
idunn/utils/result_filter.py
tests/test_result_filter.py

Allow the `search` endpoint to be a bit more permissive than `instant_answers`:
- input query can contain only prefix of the result words (without spelling mistakes)
- part of the input query is allowed not to match (at least 3 words must be relevant)

`search`: more permissive filters

---

idunn/directions/models.py

The API may return invalid values with color codes longer than 6 characters.

directions: Ignore lineColor with too many chars

---

idunn/api/instant_answer.py
tests/test_instant_answer/test_ia_api.py

In the rare case that a result selected from the geocoder response is not found in the database, `get_instant_answer_single_place` returns a 204 Response. (This was introduced by https://github.com/Qwant/idunn/pull/222).   
So the returned type was no longer consistent with its usage (leading to a server error instead of the expected 204).

instant answer: Fix an edge case when a Response was used as a Result

---

idunn/api/places_list.py
idunn/utils/categories.yml

* `pj_filters` is not defined for new categories (introduced by #67), so `pj_what` should be preferred to check that "pj" source is available for the current category
* adjustment in the query used to fetch supermarkets: some relevant POIs were missing
* allow tag "brand" to match "place_of_worship" category, due to the limitations of the current tagger

Minor adjustements about categories definitions

---

idunn/utils/result_filter.py

Match all Unicode whitespace characters as word separators, using [`\s`](https://docs.python.org/3.8/library/re.html#index-30).

result_filter: consider all whitespaces as word separators

---

idunn/blocks/images.py
tests/test_images.py

The "image" tag may contain a .jpg URL that is actually a HTML document, so the thumbnail extracted from the wikipedia article should be preferred.

images: Use wikipedia thumbnail instead of wikipedia.org URLs

---

idunn/api/search.py
idunn/utils/result_filter.py
tests/test_result_filter.py

The expected behavior is described in additional test cases.  
* a query that consists of a postcode only should match any result with that postcode.
* a postcode prefix (with at least 2 characters) should be considered as a matching word in the query.  
This is especially useful to accept "départements" numbers in France.

result_filter: Allow match on postcode only, and on postcode prefix for longer queries

---

idunn/api/constants.py
idunn/api/utils.py
idunn/geocoder/models/geocodejson.py
idunn/places/admin.py
idunn/places/base.py
idunn/places/event.py
tests/test_admin.py

This override needs to be applied on both the `GeocodingPlace` model (used by "/v1/search" and "/v1/autocomplete") and the `BasePlace` class (used by "/v1/places" and "/v1/instant_answer")

Define overridden bbox on regions where map position is unexpected

---

idunn/blocks/opening_hour.py
idunn/places/base.py

A rare server error has been observed on "/directions" when no timezone is found at the start or end point.  
`place.get_tz()` is now more robust, and duplicated code has been removed from the "opening_hour" block.

Refactor `get_tz` for Place, and handle the case when no tz is found

---

idunn/utils/result_filter.py
tests/test_result_filter.py

`coverage` could raise `ZeroDivisionError` if a field contains no word.

result_filter: Fix "coverage" for empty terms

---

.pylintrc
idunn/api/geocoder.py
idunn/api/instant_answer.py
idunn/api/search.py
idunn/datasources/pages_jaunes.py
idunn/geocoder/models/geocodejson.py
idunn/geocoder/nlu_client.py
idunn/utils/circuit_breaker.py
idunn/utils/covid19_dataset.py
idunn/utils/default_settings.yaml
idunn/utils/result_filter.py
tests/test_autocomplete.py

Query pages jaunes for all queries to instant answers (which are not tagged as addresses), if the geocoder has no result this will be used as a fallback.
This also modifies the `nlu_client` which will now have a field for the "type" of intention to help understanding the nature of the request.

instant_answer: direct queries to pages jaunes

---

idunn/api/geocoder.py
idunn/api/urls.py

This is a small optimization.   
Similarly to `/v1/instant_answer`, returning a direct `Response` bypasses the second redundant model validation that is automatically performed by FastAPI.

autocomplete: Use ORJSONResponse to skip redundant validation

---

idunn/geocoder/nlu_client.py
idunn/utils/default_settings.yaml

When using a slow or unstable network the hard-coded 300ms timeout in `nlu_client` can be rather short, this is just a tiny PR to suggest making it configurable.

add NLU_CLIENT_TIMEOUT setting

---

idunn/geocoder/nlu_client.py
tests/fixtures/autocomplete/__init__.py
tests/fixtures/autocomplete/classif_bank.json
tests/fixtures/autocomplete/classif_pharmacy.json
tests/fixtures/autocomplete/nlu/with_cat_bank.json
tests/test_autocomplete.py

This is a simple fix to avoid regressions with common abbreviation or English searches.

nlu_client: fallback through regexps when the classifier fails

---

idunn/api/categories.py
idunn/api/closest.py
idunn/api/places_list.py
idunn/api/pois.py
idunn/api/utils.py
idunn/datasources/mimirsbrunn.py
idunn/places/utils.py
idunn/utils/categories.yml
tests/conftest.py
tests/fixtures/basket_ball.json
tests/fixtures/cinema_multiplexe.json
tests/fixtures/creperie.json
tests/fixtures/fake_all_blocks.json
tests/fixtures/patisserie_peron.json
tests/test_categories.py

In "categories.yaml", the `raw_filters` (used in ES queries) are now defined with objects that accept the following keys : `class`, `subclass`, `cuisine`.   
The new `MimirPoiFilter` is responsible for translating these values into appropriate `poi_type.name` values (see https://github.com/Qwant/fafnir/pull/61)
All functions related to queries in ES for documents built by Mimirsbrunn importers are moved to "idunn/datasources/mimirsbrunn.py".
The new implementation removes a deprecated behavior about "class" filters: both `{poi_class}` and `class_{poi_class}` were accepted. The first format is obsolete. That's why a few existing fixtures need to be updated.

Extend "raw_filters" in categories definitions for OSM POIs, to allow "cuisine" filter

---

idunn/api/instant_answer.py

Calling PJ for most instant_answer requests makes the endpoint quite slower. This PR addresses part of this issue by cancelling the request to PJ if a result is already found from Bragi.

instant_answer: do not wait for pagesjaunes if bragi found an answer

---

idunn/places/base.py
idunn/places/pj_poi.py

`ResultFilter.build_params_from_place()` expects that `place.build_admins()` is iterable.

pj: Fix result_filter on PjApiPOI with no address

---

idunn/api/utils.py
idunn/blocks/__init__.py
idunn/blocks/social.py
idunn/places/base.py
idunn/places/models/pj_find.py
idunn/places/models/pj_info.py
idunn/places/pj_poi.py
tests/fixtures/orsay_museum.json
tests/test_categories.py
tests/test_pj_poi.py
tests/test_places.py

This adds new links for facebook, twitter, instagram and youtube (this last one is not really a social network but it has consequent coverage on OSM). Additionally, Facebook links won't be used anymore as websites urls (previously as a fallback for OSM and depending on the order for PJ).
~~I couldn't find any example of PJ places with an Instagram link so I didn't include it here :/~~

Add new block: social

---

idunn/places/pj_poi.py
tests/test_pj_categories.py

All categories results from pagesjaunes should now have a specified class, this allows erdapfel to [identify what to display as a category](https://github.com/Qwant/erdapfel/blob/master/local_modules/qwant-maps-common/src/place_category_name.js).
There may still be some POIs for which we display no categories, especially when performing a full-text search which is triggered when the tagger detects a brand intention).
Note that all the added classes are already recognized by erdapfel (even though I managed to break that while I was investigating on how erdapfel delt with this ... :roll_eyes:).

pj_poi: add conversion to class for all categories supported by

---

idunn/api/utils.py
idunn/blocks/__init__.py
idunn/blocks/wikipedia.py
idunn/datasources/wiki_es.py
idunn/datasources/wikidata.py
idunn/places/base.py
tests/conftest.py
tests/test_cache.py
tests/test_wiki_ES.py
tests/utils.py

Reorganize calls to the Wikipedia API to move most logic in `datasources/`, this was also an opportunity to de-duplicate the calls to Redis cache.

Add source `wiki_es`

---

idunn/blocks/__init__.py
idunn/blocks/wikipedia.py
idunn/datasources/wikipedia.py
idunn/places/base.py
idunn/utils/redis.py
tests/test_api_circuit_breaker.py
tests/test_rate_limiter.py
tests/test_wiki_ES.py
tests/test_wiki_size_limit.py

Similarly to https://github.com/Qwant/idunn/pull/261, this moves calls to Wikipedia API in its own `source` module and remove the responsibility of handling the cache from the caller.

move wikipedia wrapper into its own source

---

tests/test_accessibility.py
tests/test_brewery.py
tests/test_contact.py
tests/test_cuisine.py
tests/test_grades.py
tests/test_internet_access.py

I'm trying to get into the habit of not polluting my pull requests with some unrelated stuff, but sometime it's hard to ignore insignificant issues when you see one :no_mouth:

tests: fix tiny inconsistencies with variable names in block tests

---

idunn/api/utils.py
idunn/blocks/__init__.py
idunn/blocks/description.py
idunn/places/base.py
idunn/places/models/pj_info.py
idunn/places/pj_poi.py
idunn/utils/default_settings.yaml
tests/fixtures/pj/api_musee_picasso.json
tests/test_api_circuit_breaker.py
tests/test_pj_poi.py
tests/test_places.py
tests/test_rate_limiter.py
tests/test_wiki_ES.py

Adds a new `description` block, which contains:
- the description itself
- the source of the description (which would be helpful to display labels like "read more on Wikipedia")
- optionally, the url to the source
The information may come from several sources:
- Wikipedia if available (which means that the old `wikipedia` block is now deprecated)
- `description:lang` for OSM. Should we fallback to `decription` without a lang ? It would give much more data but at the cost of loosing some consistency with language, I'm not sure what users actually expect ? (In most case they wouldn't notice as you typically use QMaps in the country you currently live in)
- `description` for pagesjaunes, although it is only rarely available : we should ask about cases were a description is visible on their …

add block `description`

---

idunn/api/utils.py
idunn/blocks/__init__.py
idunn/blocks/delivery.py
idunn/places/base.py
idunn/places/pj_poi.py
tests/fixtures/pj/api_musee_picasso.json
tests/test_delivery.py
tests/test_pj_poi.py

Add a new `delivery` block which list 'delivery' options.
For example with [this poi](http://localhost:3000/place/pj:08692611@DARTY_Montparnasse) it outputs following block:
```json
{
"type": "delivery",
"click_and_collect": "yes",
"takeaway": "unknown",
"delivery": "yes"
}
```
EDIT: I finally added support for basic OSM tags for [`takeaway=yes`](https://taginfo.openstreetmap.org/keys/takeaway#values) and [`delivery=yes`](https://taginfo.openstreetmap.org/keys/?key=delivery#values), since it's basically free and stills ads information for respectively about 252k and 37k POIs.

add block `delivery`

---

idunn/places/base.py
tests/test_description.py

OSM's `description` block is [quite abundant](https://taginfo.openstreetmap.org/keys/description) but not integrated in https://github.com/Qwant/idunn/pull/263.
This PR supports it for a bunch of countries with a unique official language if the user language matches the local languages.
I manually referenced European Union countries together with US and UK which should cover most of our users. I didn't want to only stick to France as adding this kind of information is quite light to add in Idunn, but sadly I didn't manage to put hands on a good exhaustive database.

block/description: support OSM's `description` when country lang is known

---

idunn/api/utils.py
idunn/blocks/__init__.py
idunn/blocks/stars.py
idunn/places/base.py
idunn/places/models/pj_info.py
idunn/places/pj_poi.py
tests/fixtures/pj/api_hotel_hilton.json
tests/fixtures/pj/api_restaurant_petit_pan.json
tests/test_pj_poi.py
tests/test_stars.py

Add a new `stars` block which indicates if the POI is a starred restaurant or hotel and eventually gives its rating.
The format looks like follows:
```json
{
"type": "stars",
"ratings": [
{"has_stars": "yes", "nb_stars": 4.0, "kind": "lodging"}
]
}
```
```json
{
"type": "stars",
"ratings": [
{"has_stars": "yes", "nb_stars": null, "kind": "restaurant"}
]
}
```

add new block `stars`

---

idunn/places/pj_poi.py
tests/test_pj_poi.py

Construct `poi.meta.contribute_url` for pagesjaune's POIs. In practice this will give anchor links like https://www.pagesjaunes.fr/pros/05360257#CFMonEntreprise. However as you can see the block is hidden by the fixed page header, I see two solutions to this:
- actually provide a link to the previous element, to give an offset (I'm not a fan of this option, this is very dirty and lacks robustness)
- keep it as it is, even if not ideal, and just report the issue to pagesjaune

pj_poi: add `contribute_url` to `meta` fields

---

idunn/places/pj_poi.py

```python
if match := self.HOTEL_STARS_REGEX.match(acc.category):
```
would fail if `acc.category` is `None`.

pj_poi: Fix 'get_lodging_stars' on null category

---

idunn/places/pj_poi.py

This PR fixes a server error caused by a non-supported edge case in PJ data.
In rare cases, data returned by PJ API may contain `"address_city": null` in POI "inscriptions".   
This is consistent with the `Optional[str]` used by the data model, but breaks an implicit assumption on "admin" objects used by the result filter. The `"name"` value is assumed to be a string and is converted to lowercase:
https://github.com/Qwant/idunn/blob/f9d33b2f90a4eabfe4752bdefe1769bb2fbdef03/idunn/utils/result_filter.py#L359
https://github.com/Qwant/idunn/blob/f9d33b2f90a4eabfe4752bdefe1769bb2fbdef03/idunn/utils/result_filter.py#L199
This is a quick fix. A cleaner solution could be to use a pydantic model to validate the "admin" object upstream, before it's used by the `ResultFilter`

Fix: ignore city name 'null' in PJ API response

---

idunn/api/geocoder.py
idunn/api/search.py
idunn/api/urls.py
tests/fixtures/autocomplete/__init__.py
tests/fixtures/autocomplete/empty.json
tests/fixtures/autocomplete/paris.json
tests/test_search.py

Fix https://jira.qwant.ninja/browse/QMAPS-2199
Return 204 http response when the query is acceptable but no results are return from elasticsearch
Return 200 http response when the query is acceptable and results are return from elasticsearch OR the query is empty and no result from ES. 
We also update the query field with the actual query made to ES

Update http response for `search` endpoint

---

tests/conftest.py

I've run into an issue with my current setup (on both laptops, so that's most likely an issue with docker-compose 2.2, and not specific to my new installation), tests are able to spawn docker containers but won't be able to find them.
I've filed an issue on https://github.com/lovelysystems/lovely-pytest-docker/issues/27, but in the mean time we can explicitly set the project name in `conftest.py`. This will also spawn more human readable docker images during tests (`idunn_test-mimir_es-1` instead of `$HOME/path/to/idunn-mimir_es-1`.

explicitly set project name for tests's docker compose

---

idunn/api/instant_answer.py
idunn/geocoder/bragi_client.py
idunn/geocoder/models/geocodejson.py
idunn/geocoder/models/params.py
tests/fixtures/autocomplete/__init__.py

Update Bragi API to latest changes, mostly poi dataset name (https://github.com/CanalTP/mimirsbrunn/pull/668).

Bragi new params

---

idunn/blocks/images.py
idunn/places/base.py
idunn/utils/thumbr.py
tests/test_places.py

Rating image URLs currently expose the client to an external website, this PR wraps the images with the thumbr to keep the client's IP & cie safe.
See https://github.com/Qwant/erdapfel/pull/1278

wrap tripadvisor's ratings image in thumbr

---

idunn/blocks/images.py
tests/test_images.py
tests/test_places.py

Some images can get pretty big, especially when displaying several of
them in the list view.
If we want more granularity it could make sense to specify that as a
parameter, but I don't think this would make any improvement in our
current use.

image block: resize images images to fit what is displayed in erdapfel

---

idunn/api/instant_answer.py

As weights for TA POIs are rather high, they are already prioritized
compared to OSM POIs and this won't be too agressive by hiding potential
much more relevent OSM documents.

instant_answer: mix OSM and tripadvisor in direct query

---

idunn/api/urlsolver.py

httpx seems to have changed its behavior, and it doesn't really make
sense to raise an exception in Idunn when provided with an invalid URL
anyway.

urlsolver: do not raise an exception for 4xx/5xx and fix errors for 3xx

---

idunn/geocoder/bragi_client.py
idunn/utils/default_settings.yaml

After Idunn is deployed, the number of pending requests explodes and we reach the default limit for httpx client.

bragi client: customizable max number of connections

---

idunn/utils/prometheus.py

Calling Gauge.clear() removes the metric from output but doesn't reset
the counters.

prometheus: fix increments for async tasks

---

idunn/api/directions.py
idunn/api/urls.py
idunn/utils/default_settings.yaml
idunn/utils/default_test_settings.yaml
idunn/utils/rate_limiter.py
idunn/utils/redis.py
tests/test_directions.py
tests/test_rate_limiter.py

This should help hitting less heavily on the Redis connection pool.
I've also taken this chance to add a rate limit on the place endpoint, as it can easily expose an external API.

rate_limiter: use a single connection pool

---

idunn/blocks/reviews.py

When Author review is none, just return empty string

Fix None Author field for reviews

---

idunn/utils/rate_limiter.py
tests/test_directions.py

As we have no way to determine were the requests with no hash comes from,
there is not really any reason to perform the rate limiting for them:
- if it comes from another internal component (eg. Erdapfel), it feels
reasonable to just display a warning as said component should forward
the header.
- if the HA proxy fails to set the header value, it also feels better
to just display a warning instead of penalizing the client for the
overall traffic bandwidth.
- the only other scenario I can think of is some kind of internal stress
test, which we are currently performing, in which case it is more
convenient if the rate limiter is disabled.

rate limiter disabled for requests with no client hash

---

app.py
idunn/utils/default_settings.yaml

The app's URL prefix is currently hardcoded to `/v1`. Making this configurable would allow us to not have to use an nginx with the only purpose of rewriting `/maps/detail/v1` URLs into `/v1`.

app: makes app path prefix configurable with URL_PATH_PREFIX

---

idunn/instant_answer/patterns_to_ignore.txt

Remove query with the following pattern to display a generic IA :  Mappy / Mappy plan / Mappy itinéraire  / itinéraire Mappy

Generic ia for all maps request beginning with Mappy
