Qwant/idunn

.travis.yml, Pipfile, Pipfile.lock, README.md, api/pois.py, api/urls.py, app.py, tests/conftest.py, tests/docker-compose.yml, tests/fixtures/orsay_museum.json, tests/test_api.py
follow #1 
fetch the poi in mimir's elasticsearch.
add some test backed by docker.
=> fetch poi in elasticsearch

.travis.yml, Pipfile, Pipfile.lock, api/pois.py, api/urls.py, app.py, tests/test_api.py
init the api with some blank blocks.
will make it possible to split the work on idunn
=> Init the api

.travis.yml, Pipfile.lock, README.md, idunn/api/poi.py, idunn/api/pois.py, idunn/api/urls.py, idunn/blocks/__init__.py, idunn/blocks/opening_hour.py, idunn/blocks/phone.py, pytest.ini, tests/fixtures/orsay_museum.json, tests/test_api.py
This PR adds a basic object model structure for blocks returned by the API.
Simple tests have been added (note the json in the fixture corresponds to the bragi answer, but does not corresponds to the es answer that idunn makes).
=> Add fields - QMAPS-303

Pipfile.lock
Just update the right pipfile.lock file
=> Update pipfile.lock (fix QMAPS-303)

Pipfile.lock, idunn/api/poi.py, tests/fixtures/blancs_manteaux.json, tests/test_api.py
This fix the `Server error` when some block is null.
Not sure this is the correct way to handle it though :thinking:
=> don't add null blocks to output

idunn/api/poi.py, idunn/blocks/__init__.py, idunn/blocks/contact.py, idunn/blocks/information.py, idunn/blocks/services_and_information.py, idunn/blocks/website.py, idunn/blocks/wikipedia.py, tests/fixtures/fake_all_blocks.json, tests/fixtures/orsay_museum.json, tests/test_accessibility.py, tests/test_api.py, tests/test_api_with_wiki.py, tests/test_brewery.py, tests/test_contact.py, tests/test_full.py, tests/test_internet_access.py, tests/test_opening_hours.py, tests/test_website.py
This PR proposes to add more blocks to Idunn.
=> More blocks

app.py, idunn/utils/cors.py, tests/test_api.py
For the moment we allow any origins.
It might change afterward but I think this is enough for the moment.
=> add cors header to idunn

Pipfile, Pipfile.lock, idunn/blocks/wikipedia.py, idunn/utils/default_settings.yaml, tests/conftest.py, tests/test_api_circuit_breaker.py
Prevent too many calls to external services when they are offline.
After 15 fails we stop to invoke wikipedia api for 120 seconds.
=> Circuit breaker

idunn/blocks/wikipedia.py
Simply log the changes of states of the circuit breaker
=> Add a simple log listener

idunn/blocks/wikipedia.py, tests/test_rate_limiter.py
Based on the previous PR (https://github.com/QwantResearch/idunn/pull/24) this PR changes the behavior of Idunn when the disk is full and stops returning a wikipedia block in order to not flood the wiki api.
=> Disk space - redis

idunn/api/status.py, idunn/blocks/opening_hour.py, idunn/blocks/wikipedia.py, idunn/utils/settings.py
this way we'll be able to filter specific messages
=> use a specific logger

Pipfile, Pipfile.lock, app.py, idunn/api/place.py, idunn/api/places.py, idunn/api/poi.py, idunn/api/urls.py, idunn/utils/default_settings.yaml, idunn/utils/index_names.py, tests/conftest.py, tests/fixtures/address_du_moulin.json, tests/fixtures/admin_goujounac.json, tests/fixtures/street_birnenweg.json, tests/test_accessibility.py, tests/test_api.py, tests/test_api_circuit_breaker.py, tests/test_api_with_wiki.py, tests/test_cache.py, tests/test_full.py, tests/test_places.py, tests/test_rate_limiter.py, tests/test_wiki_ES.py
This PR adds the endpoint "/v1/places/<id>" to returns:
- admin
- street
- address
- poi
The endpoint "/v1/pois/" is deprecated by this PR.
=> New endpoint: /places/

idunn/blocks/wikipedia.py, idunn/utils/default_settings.yaml, tests/test_wiki_ES.py, tests/test_wiki_size_limit.py
Just limit the size of the wiki description to 325 chars.
No test since the changes are minimum.
=> limit wiki size

Pipfile, Pipfile.lock, idunn/blocks/opening_hour.py, tests/test_opening_hours.py
Just makes the 2 opening-hours of these 2 places correct in idunn:
- `"sunrise-sunset"` : https://www.openstreetmap.org/way/5095262
- `"24/7"` : https://www.openstreetmap.org/node/2055892768
=> Solar hours + 24/7

Pipfile, Pipfile.lock, idunn/places/place.py, tests/test_categories.py, tests/test_opening_hours.py, tests/test_places.py
* Fix `class_name` in Place `admins`
* Handle address with type `street`
* Upgrade hoh
=> Fix admins class_name

Dockerfile
Update Dockerfile
* Install git
* Run idunn app as non-root user
=> Fix and update Dockerfile

Dockerfile, Pipfile, Pipfile.lock, idunn/api/places_list.py, tests/test_categories.py
* Add 'source' field in places list response
* Upgrade "gunicorn" and "meinheld" and install them via pipenv
=> Add 'source' in list response

idunn/blocks/grades.py, idunn/blocks/images.py, idunn/places/address.py, idunn/places/base.py, idunn/places/pj_poi.py, tests/test_grades.py, tests/test_pj_poi.py
These URLs will be used to redirect the user to source data (eg on click on a photo or on a grade)
=> Return url to reviews and photos for PjPoi

README.md, idunn/api/constants.py, idunn/api/pages_jaunes.py, idunn/api/places_list.py, idunn/places/pj_poi.py, tests/test_categories.py, tests/test_pj_poi.py
* Implement "?q" query on /places (for PJ source only at the moment)
* Rename "source" constant for PagesJaunes
=> Accept text query on /places endpoint

Pipfile, Pipfile.lock, tests/test_opening_hours.py
* Upgrade humanized_opening_hours, including https://github.com/rezemika/humanized_opening_hours/pull/35
* Enable skipped test, now fixed
* Update Pipfile.lock
=> Upgrade hoh

idunn/api/closest.py, idunn/api/places.py, idunn/api/urls.py, idunn/api/utils.py, idunn/places/__init__.py, idunn/places/latlon.py, tests/conftest.py, tests/test_closest.py
I'm completely unable to test anything currently for some strange reasons. We'll have to provide a script to test or better instructions because it's a bit problematic for the moment.
=> Add reverse geocoding api

idunn/api/kuzzle.py
=> catch when http and json extract fail

idunn/api/places.py, idunn/api/urls.py, idunn/utils/default_settings.yaml, tests/test_api.py, tests/test_kuzzle.py
Linked to https://github.com/QwantResearch/erdapfel/pull/313/
=> Add CORS support

idunn/directions/client.py, idunn/utils/default_settings.yaml, tests/test_directions.py
* Define request timeout on directions
* Implement mapbox proxy for development purposes
=> directions: Implement timeout and mapbox proxy

idunn/directions/client.py
In order to monitor external calls more easily.
=> Add log message about external direction API call

idunn/directions/client.py, idunn/directions/models.py, tests/fixtures/directions/combigo_v1.1_publictransport.json, tests/test_directions.py
* Add "from" and "to" fields in `RouteLeg` model
* Return optional "id"  in "from", "to" and for each stop
=> Adapt RouteLeg model, with 'stops' containing only intermediary stops

idunn/api/kuzzle.py, idunn/api/places.py, idunn/api/places_list.py, idunn/api/status.py, idunn/api/utils.py, idunn/blocks/images.py, idunn/blocks/phone.py, idunn/blocks/services_and_information.py, idunn/directions/models.py, tests/conftest.py, tests/test_accessibility.py, tests/test_api_status.py, tests/test_brewery.py, tests/test_categories.py, tests/test_directions.py, tests/test_environment_air-quality.py, tests/test_pj_poi.py, tests/test_rate_limiter.py, tests/test_website.py, tests/test_wiki_ES.py
As black was run with different settings several times, some strange behaviors appeared with trailing commas. This is a bit prettier like this plus it will be a bit easier for me to rebase with only one run to apply.
=> fix trailing commas added by black

idunn/utils/redis.py
Fixes issue spotted by @amatissart in #96
=> Improve RedisWrapper expire parameter

idunn/api/utils.py
=> Replace post filter with query filter in wiki and reverse ES queries

idunn/blocks/covid19.py
Check if the POI exists in the Redis dataset, to add the `contribute_url` to CaResteOuvert if it exists.
=> covid19: Always add contribute_url if it exists for this poi

idunn/api/geocoder.py, idunn/utils/default_settings.yaml
Filter calls to the NLU API based on the front's language.
This is very basic, don't I miss something? ^^'
=> Add `NLU_ALLOWED_LANGUAGES` setting

idunn/geocoder/models/params.py
Calls to bragi where apparently not updated after https://github.com/CanalTP/mimirsbrunn/commit/358718af50a27c10866bd4fa35b1515eb9064a2c#diff-9cffef7612a73bc1aa4501e4ee0c2a2fR80-R82
=> focus: update mimir params naming

idunn/geocoder/nlu_client.py, idunn/utils/categories.yml
Minor improvements, and a few basic tests for the regex classifier.
=> categories: Use stricter rules to avoid false positives in regex classifier

idunn/blocks/recycling.py, tests/fixtures/recycling_response.json
Data source now returns a value between 0 and 100 for `percentage`.
=> recycling: Fix percentage value

idunn/api/utils.py, idunn/blocks/phone.py, tests/test_phone.py
=> Add more context about phone numbers parsing errors

idunn/api/instant_answer.py, idunn/api/places_list.py, idunn/api/urls.py, idunn/api/urlsolver.py, idunn/geocoder/models/geocodejson.py, idunn/geocoder/nlu_client.py, idunn/places/base.py, idunn/places/pj_poi.py, idunn/places/poi.py, idunn/places/utils.py, idunn/utils/default_settings.yaml
* uses nlu_client to detect an intention and fetch related places
* if no intention was detected, the geocoder is called directly to look for an exact match
* extend documentation
* extend tests
* implement loose matching
* ...
=> First steps for /v1/instant_answer

.github/workflows/docker.yaml, .github/workflows/tests.yml, README.md
In preparation for migrating to Qwant organization.  
Similar to https://github.com/Qwant/fafnir/pull/59
=> Define workflow to build and push docker image

idunn/api/instant_answer.py, idunn/geocoder/models/geocodejson.py, idunn/places/base.py, idunn/places/event.py, idunn/places/place.py, idunn/utils/maps_urls.py, tests/test_categories.py, tests/test_full.py, tests/test_places.py
Helper functions to build Qwant Maps URLs (implemented by Erdapfel)
are defined in `idunn/utils/maps_urls.py`
=> Define maps_place_url and maps_directions_url in place 'meta'

idunn/blocks/opening_hour.py
This is especially significant for responses where up to 40 "opening hours" blocks are evaluated.
=> optim: Fewer calls to expensive opening hours evaluation

idunn/datasources/pages_jaunes.py
* Remove URL replacement, now that `next_page_url` is correct in the response
* Add an extra margin in `max` parameter to avoid successive queries
* Remove extra whitespace in `what` parameter
=> Minor tweaks in PJ datasource

Pipfile, Pipfile.lock, app.py, pytest.ini
Each of the commits should be self-explanatory.
=> Tweaks for local testing

.pylintrc, Pipfile, Pipfile.lock, idunn/api/geocoder.py, idunn/api/instant_answer.py, idunn/geocoder/nlu_client.py, idunn/utils/result_filter.py, tests/test_instant_answer/test_ia_api.py, tests/test_result_filter.py
Add a richer filter for results, among things that remain to do:
I didn't attempt to considering the order of the terms as I think it would be much more complicated to filter out only a few specific cases, is this fair?
=> instant answer: more permissive filter

idunn/blocks/website.py, idunn/places/base.py, tests/test_phone.py
* Read `contact:mobile` as fallback for phone number
* Read `contact:facebook` as fallback for website
* Split phone numbers separated by `;` in tags and keep the first one
=> Handle more contact tags

idunn/api/instant_answer.py, idunn/utils/result_filter.py, tests/test_result_filter.py
=> result_filter: re-rank results when query order is not be reflected

idunn/utils/categories.yml
Update the `health` category to match consistently hospitals and clinics.
The only strange remaining category is `service` which only contains most offices :/
=> categories: update health filters

idunn/datasources/pages_jaunes.py, idunn/utils/default_settings.yaml
Add a timeout to pagejaune calls.
=> settings: add PJ_API_TIMEOUT

idunn/places/pj_poi.py, tests/test_images.py
This case was not properly tested in #231. My bad :weary:
=> Fix images block on PjApiPOI without image

idunn/api/urls.py, idunn/utils/default_settings.yaml, idunn/utils/rate_limiter.py
Similar to the rate limits mechanism used on directions endpoints.
=> Define RL limits for get_places_bbox

idunn/datasources/pages_jaunes.py, tests/fixtures/autocomplete/__init__.py, tests/fixtures/autocomplete/nlu/with_picasso.json, tests/test_instant_answer/test_ia_api.py, tests/test_pj_poi.py, tests/utils.py
https://github.com/Qwant/idunn/pull/235 was missing a least of testing, so here it is!
=> instant_answer: add test for pages_jaunes's fallback mechanism

idunn/utils/categories.yml
Querying PJ for "clubs de sport* seems to give better results.
| master | HEAD |
|-|-|
| ![Screen Shot 2021-06-17 at 18 07 06](https://user-images.githubusercontent.com/1173464/122434155-230d0800-cf97-11eb-913a-8c9496bef555.png) | ![Screen Shot 2021-06-17 at 18 06 33](https://user-images.githubusercontent.com/1173464/122434178-27d1bc00-cf97-11eb-9574-b66a5f9200b1.png) |
=> categories: update PJ request for sports_centre

idunn/datasources/pages_jaunes.py
`ApiPjSource.search_places()` (used by instant answers) may log an error about text queries that fail to be parsed correctly by the API. These HTTP errors with status 400 are quite common and are not useful in practice.
This PR introduces a new optional paramater `ignore_status` to log this specific error with the `debug` level.
=> pj: Reduce log level for HTTP errors about unrecognized query pattern

idunn/blocks/transactional.py, idunn/utils/default_settings.yaml
A new setting to enable/disable the block introduced by #250
=> Define flag in settings to enable 'transactional' block

Pipfile, Pipfile.lock, idunn/api/hotel_pricing.py, idunn/api/urls.py, idunn/datasources/tripadvisor.py, idunn/places/models/ta_api_reponse.py, idunn/utils/default_settings.yaml, tests/conftest.py, tests/docker-compose.yml, tests/fixtures/ta/__init__.py, tests/fixtures/ta/api_search_by_hotel_id_the_hotel_captain_cook.json, tests/fixtures/ta/api_search_by_location_id_the_hotel_captain_cook.json, tests/test_tripadvisor_hotel_pricing.py
Even if it will not be used in the short term, we can keep it.
Add `hotel_pricing` route to call hotel pricing Tripadvisor api with correct parameters
Probably missing LRU cache
=> Hotel pricing Tripadvisor api endpoint

idunn/datasources/osm.py, idunn/datasources/tripadvisor.py, idunn/places/__init__.py, idunn/places/base.py, idunn/places/poi.py, idunn/utils/place.py, tests/fixtures/tripadvisor_cinema_multiplexe.json, tests/test_accessibility.py, tests/test_contact.py, tests/test_covid19.py, tests/test_delivery.py, tests/test_description.py, tests/test_images.py, tests/test_opening_hours.py, tests/test_phone.py, tests/test_stars.py, tests/test_website.py
Add MCID tripadvisor url in `PlaceMeta` object with `source_url` and `contribute_url` fields
Notice, I keep PlaceMeta object for Tripadvisor even if `contribute_url` doesn't make sense for Tripadvisor. I can change if neccessary
=> Add MCID tripadvisor url

idunn/api/instant_answer.py, tests/fixtures/autocomplete/tripadvisor/hotel_moliere.json
Fix instant answer with the new Bragi version (json bragi response change)
=> Fix instant answer for poi without intention

idunn/api/closest.py, idunn/api/places.py, idunn/api/status.py, idunn/datasources/mimirsbrunn.py, idunn/utils/default_settings.yaml, idunn/utils/es_wrapper.py, idunn/utils/place.py, tests/fixtures/autocomplete/__init__.py, tests/fixtures/bragi_status.json, tests/fixtures/nlp/classifier_body.json, tests/fixtures/nlp/tagger_body.json, tests/fixtures/pj/__init__.py, tests/fixtures/wiki_es_successful_response.json, tests/test_api_status.py
heathcheck for : 
- es_mimir
- es_wiki
- bragi
- taggeur
- classifier
- pagesjaunes
- redis
=> add heathcheck for all external sources

idunn/places/base.py, idunn/places/place.py, tests/test_categories.py, tests/test_full.py, tests/test_pj_poi.py, tests/test_places.py
This will help implementing the instant answer module which uses a raw
bubble image and display its own icon which depends on the user theme
(dark/light).
=> tripadvisor: add rating_url_noicon in meta

idunn/api/instant_answer.py, idunn/utils/prometheus.py
Some tasks appears to be hanging in the pool forever, this might fix the issue but it also adds some prometheus metrics to help future investigations.
=> fix PJ pending task and add async tasks metric

idunn/api/instant_answer.py, idunn/geocoder/nlu_client.py, idunn/utils/default_settings.yaml
Remove : `IA_SUCCESS_ON_GENERIC_QUERIES` and `IA_CALL_PJ_POI` flag
=> Clean Instant answer old flag

Pipfile.lock, idunn/api/places.py, idunn/api/search.py, idunn/datasources/osm.py, idunn/datasources/pages_jaunes.py, idunn/datasources/tripadvisor.py, idunn/directions/client.py
Starlette dep is not required anymore and could be replaced
=> Remove starlette dependency

Pipfile.lock, idunn/api/places.py, idunn/api/search.py, idunn/datasources/osm.py, idunn/datasources/pages_jaunes.py, idunn/datasources/tripadvisor.py, idunn/directions/client.py
This reverts commit a01ce05090e4d3fd7a3d8ff676a0242136c11397.
=> Revert "Remove starlette dependency (#326)"

idunn/api/instant_answer.py
We want to know IA source response portion for data analysis
=> Add source IA response log

end_to_end/instant_answer.py, idunn/utils/default_test_settings.yaml, idunn/utils/settings.py
Add local end-to-end tests to validate a set of instant answer
=> Add local IA end to end tests

idunn/utils/categories.yml
Add new categories from the new classifier version
=> Add new categories

end_to_end/Readme.md, end_to_end/instant_answer.py, idunn/api/instant_answer.py, idunn/geocoder/nlu_client.py, tests/test_instant_answer/test_ia_api.py
This PR should get result for 'tour Eiffel', 'tour de pise' from OSM for instant answer
=> Call OSM on single Instant answer for admin or poi with wikidata information 

idunn/blocks/reviews.py, idunn/places/base.py, idunn/places/poi.py
- Use tripadvisor base url instead of the full poi url as review root url 
- Add ancre "REVIEWS" to build "all reviews" url
=> Use tripadvisor base url instead of the full poi url as review root url

idunn/api/geocoder.py, idunn/api/instant_answer.py, idunn/api/search.py, idunn/datasources/__init__.py, idunn/datasources/osm.py, idunn/datasources/pages_jaunes.py, idunn/datasources/tripadvisor.py, idunn/geocoder/models/geocodejson.py, idunn/geocoder/nlu_client.py, idunn/utils/categories.yml, idunn/utils/category.py, idunn/utils/default_settings.yaml, idunn/utils/default_test_settings.yaml, tests/test_autocomplete.py, tests/test_instant_answer/test_ia_api.py, tests/test_search.py
=> Clean nlu intention

idunn/api/instant_answer.py, idunn/datasources/pages_jaunes.py, idunn/datasources/tripadvisor.py
- Call tripadvisor outside france
-  Don't call PJ outside france
=> Fix call search endpoint

idunn/datasources/directions/hove/client.py
Current behavior was to rely on raise_for_status which would just raise
a 500 and not be very informative.
=> catch 4xx status codes from Hove

idunn/utils/categories.yml
=> Add airport category

idunn/datasources/directions/hove/models.py, idunn/instant_answer/patterns_to_ignore.txt
Remove empty instruction on public transport without name and distance equal to 0
=> Remove empty instruction on public  transport 
